### ISSUE TITLE
Top nav: unclear what page user is on

### ISSUE THREAD

**Issue by erikanoms** [VIDA-NYU/reproserver#64]
3: Major Usability Problem
There is no indication at the top navigation bar to let the users know what page they're on. A small dot under the menu items would make it clear.
<img width="233" alt="Screen Shot 2022-08-18 at 12 27 53" src="https://user-images.githubusercontent.com/94011156/185446610-faeb5294-63c8-4004-88e5-8e4ec01b042c.png">

**Comment by remram44** [comment]
The current site map is like this:

* Index page (has upload form to send an RPZ or a URL to an RPZ to be reproduced)
  * Reproduce page: an RPZ file was selected (has form to set parameters, expose ports, replace input files)
    * Results page: parameters were set for an RPZ, experiment is running (showing log) or complete (showing log in collapsible box and output files)
  * Web capture page (has upload form to send an RPZ)
    * Web capture dashboard: an RPZ file was selected, and a WACZ was uploaded or created (has buttons to crawl, record, upload WACZ, preview, download web-RPZ)
      * Crawl: show status of crawl (when done, sends you back to web capture dashboard with new WACZ)
      * Record: similar to Results page but with webrecorder embed (upload button sends you back to web capture dashboard with the new WACZ)
      * Upload WACZ (select a WACZ and click upload, sends you back to web capture dashboard with new WACZ)
      * Preview: same as Results page but with the new WACZ

![screenshot of navbar](https://user-images.githubusercontent.com/426784/188019657-a288f115-fda6-4b13-8ebf-3b64df6c41ab.png)


Maybe breadcrumbs would be more appropriate to show where we are in the tree, rather than using the navbar? And then we could just put "reproduce" / "web capture" / "about" / "links" in the navbar?

![imaginary screenshot](https://user-images.githubusercontent.com/426784/188020177-12d48ac3-42c2-41ee-a306-3d8d6ed6de37.png)

**Comment by erikanoms** [comment]
This is great! I love the simplified nav bar. Thank you
